### ISSUE TITLE
Don't compile

### ISSUE THREAD

**Issue by VincentMolinie** [mazzeb/gradle-auto-version#1]
Hi,

When I try to use your plugin I get:
```
> Failed to notify project evaluation listener.
   > com.google.gson.Gson.newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;
```

What am I doing wrong ?

**Comment by mazzeb** [comment]
Hi,
i cannot reproduce your issue. Have you created a `version.json` file in your project root? Which gradle version are you using?

**Comment by VincentMolinie** [comment]
I think it's because I'm using gradle tools 3.0.0
